### ISSUE TITLE
They do the same thing. 

### ISSUE THREAD

**Issue by DrMadWill** [RavanM/FrontendL#1]
https://github.com/RavanM/FrontendL/blob/3b3580e0f5979fc9a2b723aa5ec45ee1f7f7d9c6/Lesson5/task2.html#L13
burdaki `div` daxil olmaqla aşğıdakı `div` eyni iş görür bunu üçün eyni classı versən daha yaxşı olar. Amma düşünürəmki css selectorları anlmaq  etmisən.

**Comment by RavanM** [comment]
qarışıqlıq yaradırdı əvvəllər ona görə ayrı-ayrı ad verirdim. İndi yavaş-yavaş düzəltməyə çalışıram
