### ISSUE TITLE
Class Name

### ISSUE THREAD

**Issue by DrMadWill** [RavanM/FrontendL#2]
class adları balaca həriflə başlayır.
https://github.com/RavanM/FrontendL/blob/3b3580e0f5979fc9a2b723aa5ec45ee1f7f7d9c6/Lesson6/index.html#L11
https://github.com/RavanM/FrontendL/blob/3b3580e0f5979fc9a2b723aa5ec45ee1f7f7d9c6/Lesson6/index2.html#L11

burada class adi left rigt versən daha məqsədə uyğun olacaq.
https://github.com/RavanM/FrontendL/blob/3b3580e0f5979fc9a2b723aa5ec45ee1f7f7d9c6/Lesson6/index2.html#L12
https://github.com/RavanM/FrontendL/blob/3b3580e0f5979fc9a2b723aa5ec45ee1f7f7d9c6/Lesson6/index2.html#L17

**Comment by RavanM** [comment]
bunu demişdiz dərsdə .son tapşırıqlarda düzəltmişəm
